version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:28017"
  my-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-go-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
